version: '2'
services:
  app1-app:
    image: app1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${accelerator.registry.password}@accelerator-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${accelerator.registry.password}@accelerator-registry:8761/config
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  accelerator-registry:
    extends:
      file: accelerator-registry.yml
      service: accelerator-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
